# Generated by Django 3.2.7 on 2021-09-16 08:58

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='date_modificado',
        ),
        migrations.CreateModel(
            name='importCNAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to=core.models.create_path_import_file)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
