# Generated by Django 3.2.7 on 2021-09-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210916_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='document',
        ),
        migrations.AlterField(
            model_name='importcnad',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner'),
        ),
    ]
