# Generated by Django 3.2.7 on 2021-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210916_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionstore',
            name='documentRecipient',
        ),
        migrations.RemoveField(
            model_name='transactionstore',
            name='numberCard',
        ),
        migrations.AddField(
            model_name='owner',
            name='document',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='transactionstore',
            name='number_card',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
