# Generated by Django 3.2.7 on 2021-09-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210916_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importcnad',
            name='store',
        ),
    ]
