# Generated by Django 3.2.7 on 2021-09-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_importcnad_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstore',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.importcnad'),
        ),
    ]
