# Generated by Django 3.2.7 on 2021-09-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transactionstore_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='importCNAD',
            new_name='ImportCNAB',
        ),
    ]
